# src/ai_recommender.py

"""
This file connects the application to a local Ollama model.

Main purpose:
- Send the structured log analysis result to a local LLM
- Generate an AI-assisted root-cause explanation
- Generate practical troubleshooting recommendations
"""

import requests


OLLAMA_API_URL = "http://localhost:11434/api/generate"
DEFAULT_MODEL = "qwen2.5:1.5b"


def build_ai_prompt(report):
    """
    Build a clear prompt for the local AI model.

    Parameters:
        report (dict): Troubleshooting report generated by the application.

    Returns:
        str: Prompt text for the local AI model.
    """

    detected_lines = "\n".join(report["detected_error_lines"])

    secondary_categories = (
        ", ".join(report["secondary_categories"])
        if report["secondary_categories"]
        else "None"
    )

    prompt = f"""
You are a CI/CD troubleshooting assistant.

Analyze the following pipeline log analysis result and provide a professional recommendation.

Log file:
{report["file_name"]}

Detected error lines:
{detected_lines}

Primary failure category:
{report["primary_category"]}

Secondary categories:
{secondary_categories}

All detected categories:
{", ".join(report["all_detected_categories"])}

Confidence level:
{report["confidence_level"]}

Severity level:
{report["severity_level"]}

Rule-based probable root cause:
{report["probable_root_cause"]}

Rule-based suggested fix:
{report["suggested_fix"]}

Please respond in this format:

AI Root Cause Explanation:
Explain the most likely root cause in simple professional language.

Recommended Fix Steps:
Give 3 to 5 practical steps to fix the issue.

Developer Notes:
Mention what the developer should check first.
"""

    return prompt


def generate_ai_recommendation(report, model_name=DEFAULT_MODEL):
    """
    Generate an AI-assisted recommendation using local Ollama.

    Parameters:
        report (dict): Troubleshooting report.
        model_name (str): Ollama model name.

    Returns:
        str: AI-generated recommendation text.
    """

    prompt = build_ai_prompt(report)

    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(
            OLLAMA_API_URL,
            json=payload,
            timeout=120
        )

        response.raise_for_status()

        result = response.json()
        return result.get("response", "No AI recommendation was generated.")

    except requests.exceptions.ConnectionError:
        return (
            "Local AI recommendation is unavailable because Ollama is not running. "
            "Please start Ollama and make sure the local model is available."
        )

    except requests.exceptions.Timeout:
        return (
            "Local AI recommendation timed out. "
            "Try again or use a smaller/faster Ollama model."
        )

    except requests.exceptions.RequestException as error:
        return f"Local AI recommendation failed: {error}"
    

def check_ollama_status(model_name=DEFAULT_MODEL):
    """
    Check whether Ollama is running and whether the selected model is available.

    Parameters:
        model_name (str): Ollama model name.

    Returns:
        dict: Status information about Ollama and the model.
    """

    try:
        response = requests.get(
            "http://localhost:11434/api/tags",
            timeout=5
        )

        response.raise_for_status()

        result = response.json()
        models = result.get("models", [])

        available_models = [
            model.get("name", "")
            for model in models
        ]

        model_available = model_name in available_models

        return {
            "ollama_running": True,
            "model_available": model_available,
            "available_models": available_models,
            "message": (
                f"Ollama is running and model '{model_name}' is available."
                if model_available
                else f"Ollama is running, but model '{model_name}' is not available."
            )
        }

    except requests.exceptions.ConnectionError:
        return {
            "ollama_running": False,
            "model_available": False,
            "available_models": [],
            "message": "Ollama is not running. Please start Ollama and try again."
        }

    except requests.exceptions.Timeout:
        return {
            "ollama_running": False,
            "model_available": False,
            "available_models": [],
            "message": "Ollama status check timed out."
        }

    except requests.exceptions.RequestException as error:
        return {
            "ollama_running": False,
            "model_available": False,
            "available_models": [],
            "message": f"Ollama status check failed: {error}"
        }